#!/usr/bin/bash


clear


echo -e "\t\t\tWelcome to Cho-I-Chop Bank\n" 
echo -e "\n*********************************************\n" #the stars make password hiden
echo -e "\t\t\tplease enter your PIN\n"
read -s customer_pin #s stand for secrete


echo $customer_pin


current_account_balance=5000000000000

#menu selection
echo "select an operation to perform"
echo -e "\n1) withdraw \n2) Deposit \n3) check_Balance"
read -p "Enter 1,2 or 3:" menu_selection

# withdrawal

read -p "HOw much do you want to withdraw: " amount_to_withdraw  # amount_to_withdraw=450000
remaining_balance=`expr $current_account_balance - $amount_to_withdraw`
echo $remaining_balance

# Deposit

read -p "HOw Much money would you like to deposit?" amount_to_deposit
new_balance=`expr $remaining_balance + $amount_to_deposit`
echo "YOur new account is ${new_balance}"

# Account Balance 
echo "your account balance ${new_balance}"
