#!/bin/bash
clear
PS3="Your choice: "
select ITEM in "Add user" "List All Processes" "Kill Processs" "Install Programs" "quit"
do
if [[ $REPLY -eq 1 ]]
then
        read -p "Enter username: " username
        output="$(grep -w $username /etc/passwd)"
        if [[ -n "$output"  ]]
        then
                echo "The username $username already exists."
        else
                Sudo useradd -m -d /bin/bash "$username"
                if [[ $? -eq 0 ]]
                then
                       echo "The user $username was added successfully."
                       tail -n 1 /etc/passwd
               else
                       echo "There was an error adding the user $username."
               fi
        fi
elif [[ $REPLY -eq 2 ]]
then
        echo "Listing all Processes....."
        sleep 1
        ps -ef
elif [[ $REPLY -eq 3 ]]
then
        read -p "Enter the process to kill: " process
        pkill $process
elif [[ $REPLY -eq 4 ]]
then
        read -p "Enter the program to install: " app
        sudo apt update &&  sudo apt install $app

elif [[  $REPLY -eq 5 ]]
then
        echo "Quitting..."
        sleep 1
        exit
else
        echo "Invalid menu selection!!"
fi



done
